### PR TITLE
top nav idea

### PR DESCRIPTION
**Pull request by pelusodan**
image

Maybe?? looks a little neat - what do folks think? Worth exploring this path?

### CODE REVIEW

**Comment by austinengel17** [comment]
I like it although I cant tell if I like the more simplistic trashy looking website with a nav bar in the corner and full white background like this

Screen Shot 2023-09-06 at 12 22 07 AM

**Comment by pelusodan** [comment]
@austinengel17 i fuck w this one hard - gonna update at some point today. Is that screenshot from a local build or something you made w a photo editor?

**Comment by austinengel17** [comment]
A screenshot with text added through an editor. Been working on a nav component, have no idea if its gonna work lmao

**Comment by pelusodan** [comment]
> A screenshot with text added through an editor. Been working on a nav component, have no idea if its gonna work lmao

image
just updated the branch to look like this - much cleaner imo

**Comment by pelusodan** [comment]
:shipit:

**Pull request merged**
